repository : keivanz/keivanz_personal_site
github     : [metadata]

# logo: https://keivanz.github.io/assets/img/favicons/favicon-32x32.png

# ==========
# SITE TITLE
# ==========
title: Keivan Zolfaghari
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to your new site, replace this description

# =======
# BASEURL
# =======
#
# This is the subpath of your site, e.g. /blog if you want users to 
# access your site at https://example.com/blog
#
# If you are using a gh-pages site this will be empty if your site 
# is on https://username.github.io if your repo using this theme is 
# named "foobar" then change this to /foobar and when you serve
# it using the pages setting it will be live at
#
# https://username.github.io/foobar 

baseurl       : "https://keivanz.github.io"

# ===
# URL
# ===
#
url            : "https://keivanz.github.io"

sass:
  style: expanded

exclude:
  - 'README.md'

# ==============
# BUILD SETTINGS
# ==============
#
# These are build settings needed for when you run "jekyll serve"
# commands. You can change these, but be careful because they can
# cause your site to break.
#
# COLLECTIONS
# ===========
#
# Collections are Jekylls way to handle things like tags, categories,
# authors. Any type of data you can iterate over. Here is how you add
# categories to your blog. Uncomment this to have it assign links for
# your categories
# 
# collections:
#   categories: # This will create your category links
#     output: true
#     permalink: /:categories/:title/
#
# =======
# PLUGINS
# =======
# This is just one of the plugins you can use with jekyll
# you can find more useful plugins I have created at: 
# 
# https://github.com/jekyllgems/plugins

plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-redirect-from


  quotes:
  - "The only way to do great work is to love what you do. – Steve Jobs"
  - "Life is what happens when you're busy making other plans. – John Lennon"