repository : keivanz/keivanz_personal_site
github     : [metadata]

# =============
# SOCIAL LINKS 
# =============
#
# This section handles your social network links displayed across
# your site in liquid tags as site.social.NAME feel free to reach
# out to me using these if you need any help.

social:
  twitter          : jekyllcoder
  github           : leatheresque
  email            : jekyllcoder@gmail.com

logo: https://keivanz.github.io/keivanz_personal_site/assets/img/favicons/favicon-32x32.png



# ==========
# SITE TITLE
# ==========
#sass:
 # style: compressed
# This is the title of your website for example, "The Moo York Times" :)

title: Keivan Zolfaghari

description: >- # this means to ignore newlines until "baseurl:"
  Welcome to your new site, replace this description

# =======
# BASEURL
# =======
#
# This is the subpath of your site, e.g. /blog if you want users to 
# access your site at https://example.com/blog
#
# If you are using a gh-pages site this will be empty if your site 
# is on https://username.github.io if your repo using this theme is 
# named "foobar" then change this to /foobar and when you serve
# it using the pages setting it will be live at
#
# https://username.github.io/foobar 

baseurl       : "https://keivanz.github.io/keivanz_personal_site"

# ===
# URL
# ===
#
# This is the base hostname & protocol for your site, as you see 
# I use https://jekyllgems.github.io because this is a template 
# and served live on my gh-pages site.
#
# Use localhost for local development
# http://localhost:4000


url            : "https://keivanz.github.io/keivanz_personal_site"

include:
  - 'assets'
  - 'pages'

assets:
    - "*"

exclude:
  - 'README.md'

# ==============
# BUILD SETTINGS
# ==============
#
# These are build settings needed for when you run "jekyll serve"
# commands. You can change these, but be careful because they can
# cause your site to break.
#
# COLLECTIONS
# ===========
#
# Collections are Jekylls way to handle things like tags, categories,
# authors. Any type of data you can iterate over. Here is how you add
# categories to your blog. Uncomment this to have it assign links for
# your categories
# 
# collections:
#   categories: # This will create your category links
#     output: true
#     permalink: /:categories/:title/
#
# =======
# PLUGINS
# =======
#
# This is just one of the plugins you can use with jekyll
# you can find more useful plugins I have created at: 
# 
# https://github.com/jekyllgems/plugins

plugins:
  - jekyll-feed